### ISSUE TITLE
Peer Review #1

### ISSUE THREAD

**Issue by Junbo345** [thk421/property_crimes_data#1]
Opening statement summary:

I am peer reviewing Tina’s paper on An Analysis of Home Invasion and Property Theft Crimes in Toronto before and after COVID-19.

Strong positive points:

Nice start! The topic sounds attractive to me and the intro is solid and well-structured. Also, I can see citations in the paper and the scripts for simulation and data cleaning. 

Critical improvements needed:

The paper is not finished yet, so try to finish it ASAP  to allow others to provide more detailed feedback on the entire paper and Git repository.

Suggestions for improvement:

Please consider adding/changing/removing:

1. Finish the paper
2. Fix citations: I can see that there is some error in your paper about citations (like ?@...) I have encountered this before. This issue could be due to an unsaved .bib file before rendering. 
3. The abstract is good, but you can add one more sentence in front to talk about the broader background of the context you are talking about. In this case, the crimes in Toronto. 
4. Be sure to add your git link to the paper. 
5. Remember to cite R and other packages
Evaluation:

Estimated mark: 0 since it is not finished

Reason:
I give you 0 since your R citation is not added but I think you have a good start, make sure you finish it and check the rubrics with your paper. Good luck!

**Comment by thk421** [comment]
All issues were fixed.
